# Generated by Django 3.0.1 on 2020-01-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=8)),
                ('userid', models.CharField(max_length=6)),
                ('account_encrypted', models.BinaryField(max_length=4096)),
            ],
        ),
    ]
